### ISSUE TITLE
Running code like the example gives an error

### ISSUE THREAD

**Issue by Wangmmx** [paritytech/txwrapper#167]
This is my code, When I run the transfer, an error occurs
`Error: Struct: failed on 'metadata':: Cannot map Enum JSON, unable to find 'registry' in v0, v1, v2, v3, v4, v5, v6, v7, v8, v9, v10, v11`,

I can’t find the problem. Can you plaese help me? I’ve been working on the offline transaction body for a week. No one is willing to reply to the issue of polkadot now. I’m so happy to see the offline method here. I hope you can help me

```
...

        const { block } = await api.rpc.chain.getBlock();
        const blockHash =  await api.rpc.chain.getBlockHash(block.header.number);
        const genesisHash =  await api.rpc.chain.getBlockHash(0);
        const metadataRpc = await api.rpc.state.getMetadata();
        const nonce = (await api.query.system.account('5FA5GKjtaCYHRhLtJ8bWhA1zP137PzTMmiDw8nfb5wDXSyGD')).nonce;
        const { specVersion, transactionVersion } = await api.rpc.state.getRuntimeVersion();
        const registry = getRegistry('Westend', 'Westend', specVersion, metadataRpc);
        const unsigned = methods.balances.transfer(
            {
                value: 7,
                dest: '5GXvoYbSd2VZeabSY63mGdGJc6bDrmZg5mTz78ueEhKMAivm',
            },
            {
                address: '5FA5GKjtaCYHRhLtJ8bWhA1zP137PzTMmiDw8nfb5wDXSyGD',
                blockHash,
                blockNumber: registry
                    .createType('BlockNumber', block.header.number)
                    .toNumber(),
                eraPeriod: 64,
                genesisHash,
                metadataRpc,
                nonce, // Assuming this is Alice's first tx on the chain
                specVersion,
                tip: 0,
                transactionVersion,
            },
            {
                metadataRpc,
                registry,
            }
        );

```

**Comment by Wangmmx** [comment]
Thank you in advance for taking the time to help me in your busy schedule, thank you very much

**Comment by Wangmmx** [comment]
Solved by changing the `metadataRpc` to `metadataRpc.toHex()` .
Got the serialize transaction and submit , got error
`createType(Extrinsic):: createType(ExtrinsicV4):: createType(ExtrinsicSignatureV4):: Unable to create Enum via index 207, in Ed25519, Sr25519, Ecdsa` 
Do not know what is wrong.

here's the tx:
`0x2d0284ff88ccfe1c52268e4f5dfb6228e71b2cff7a24446fad25fcd2bc3481fad2c63ccf0099e5d7bd5dbe6cfe2d60519fd407e124ce82741cad801d1a76ff837580c0338317f8f087daa265cbbd3c1f6a4f75ce3c963b26c2510fd7903e2f46c75e06eb04c50304000400ffc5b423eea8b3438b5d16f8d34c2a54f2b7a8b65194d5d88a5fda9966de8b286a1c`

**Comment by Wangmmx** [comment]
could you please help me? please :(

**Comment by Wangmmx** [comment]
I assembled the transaction according to the method in the example, and successfully generated the serialized transaction, but the broadcast has always reported an error, can you help me to see it, I am sorry to disturb you, I have no other way, I can’t figure it out. , Thank you sincerely!
@jacogr  @amaurymartiny

**Comment by jacogr** [comment]
Sorry, really not familiar with the code structure of the txwrapper (or even what it does) myself, so clueless to guidance on usage thereof.

Having said that, basically that would mean that your code generates a tx with the wrong address type, so you need to specify the Address type correctly using whatever the toolkit provides - https://polkadot.js.org/api/start/FAQ.html#i-cannot-send-transactions-from-my-node-template-based-chain

**Comment by Wangmmx** [comment]
Um, I failed to assemble some transactions offline, and then I didn’t wait for your reply. I saw that there is a way to provide offline, I tried this method. My previous problem is here, I haven’t solved it yet, I will always I have tried hard. 
https://github.com/polkadot-js/api/issues/2330

I really appreciate your reply. I am looking forward to your reply these days. Okay, let me first check the type of address you said. Thank you very much!

**Comment by Wangmmx** [comment]
Where do I need to add my Address type? I did not connect my own node, I just assembled the transaction body by myself

**Comment by jacogr** [comment]
Like I said, I don't know how this pieces together, but generally you have 2 options -

- into the API constructor via `types` as an option
- into the registry via registry.register

Leaving this issue now before I get myself into trouble, since I just don't know where here, so even more clueless that you when it comes to this repo and intended use.

**Comment by Wangmmx** [comment]
Okay sorry, I won't ask you again, this may be really too difficult for me, I really should give up, sorry for disturbing you these days
