### ISSUE TITLE
Submit Extrinsic:  Bad Proof

### ISSUE THREAD

**Issue by Wangmmx** [paritytech/txwrapper#171]
The signature is a 65-bit signature in multi-sign format, the last 64 bits at https://polkadot.js.org/apps/#/ Toolbox/sign verification here is correct, do not know which parameters are wrong, thanks for the help

here's my code, from the example, only the data is different
```
...
        const unsigned = methods.balances.transfer(
            {
                value: 1,
                dest: to,
            },
            {
                address: from,
                 blockHash: blockHash.toHex(),
                 blockNumber: registry.createType('BlockNumber', block.header.number).toNumber(),
                 eraPeriod:64,
                genesisHash: genesisHash.toHex(),
                metadataRpc: metadataRpc,
                nonce, 
                specVersion,
                tip: 0,
                transactionVersion
            },
            {
                metadataRpc,
                registry
            }
        );
        console.log('unsigned', unsigned);

        const signingPayload = createSigningPayload(unsigned, {metadataRpc, registry});

        const extrinsicPayload = registry.createType('ExtrinsicPayload', signingPayload, {version: TRANSACTION_VERSION});
        let sig = pair.sign(hex.hexToU8a(extrinsicPayload.toHex()), {withType: true});

        const tx = createSignedTx(unsigned, sig, { metadataRpc, registry });
        console.log(`\nTransaction to Submit: ${tx}`);
...
```

**Comment by joepetrowski** [comment]
Can you try two things:

1. Right after you declare your registry, run this: 
  `registry.setMetadata(createMetadata(registry, metadataRpc));`
2. Change your signature to be `const { signature } = extrinsicPayload.sign(pair);`

**Comment by Wangmmx** [comment]
I changed the signature in another way and solved!, thank you very much! I don't quite understand why the two signature methods are different

at https://polkadot.js.org/apps/#/toolbox/sign, I fill in the payload, and then execute the signature, the signature obtained is not the same as my successful siganature

**Comment by joepetrowski** [comment]
I'm not sure of the internals of signing methods, but I do know that bad proof comes from not having the correct signed extensions in the registry (which `.setMetadata()` takes care of).

**Comment by Wangmmx** [comment]
Um, because I used the method in the browser to verify the signature before, so I didn't expect that the signature will be different. Thank you very much! I will find out more about this signature by myself, and I am very happy now, thanks again , and close this issue.
