### ISSUE TITLE
Error broadcasting transaction

### ISSUE THREAD

**Issue by shawn0322** [paritytech/txwrapper#195]
1010 Invalid Transaction: "Transaction has a bad signature"

**Comment by danforbes** [comment]
Hi, @shawn0322 - we will need some more details to be able to answer your question. We are working on better Issue templates, but please refer to this document in the meantime https://stackoverflow.com/help/how-to-ask It's possible you're running into a problem related to SCALE types and if that's the case you may find some help here https://polkadot.js.org/api/start/FAQ.html In particular, you may want to try registering the `Address` and `Lookup` types https://polkadot.js.org/api/start/FAQ.html#i-cannot-send-transactions-from-my-node-template-based-chain

**Comment by shawn0322** [comment]
Use @substrate/txwrapper@3.5.1
Use Westend
Build the transaction based on the example 。  polkadot.ts 


0x250284a2c35bcf18b8ba520258d127a5a74f3ea902086027e3d6033d6f8da38daf374601ae9261f2c986e43c9abad0a185d9ca32db7a58bd49284e3cc775a479f3131266ad8dfa6f866c6113d109bc8a558d0b8108c3f37bc3ada62c986a9dd9de6f89882500000005008eaf04151687736326c9fea17e25fc5287613693c912909cb226aa4794f26a4830

Error broadcasting transaction：

![image](https://user-images.githubusercontent.com/38547567/88383473-27f42680-cddd-11ea-850e-1b2aa7eeced4.png)

**Comment by shawn0322** [comment]
![image](https://user-images.githubusercontent.com/38547567/88383572-596cf200-cddd-11ea-9724-e5721c50af64.png)



Decoded Transaction
  To: 5EhEzn2HBma89WCtmAMisKvnQNtMKTs8RTMT5Ynv3Z8FMGMx
  Amount: 0

Payload to Sign: 0x8c04007456209b3bd8230c0db53ca22f3f1ebc59060c3d1060b29f407d655ca0c73a42006502000008000000e143f23803ac50e8f6f8e62695d1ce9e4e1d68aa36c1cd2cfd15340213f3423e4f57aa1c466b8ec528bb8844f38ea536e4d6b033eff3b2a102bc76f7a9178451

Decoded Transaction
  To: 5EhEzn2HBma89WCtmAMisKvnQNtMKTs8RTMT5Ynv3Z8FMGMx
  Amount: 0

Signature: 0x01483454de8b9f1ee4ec54cc11c6896fcc3804b1a8ddb84a45e5a0f96ae88ebf28f03253bc1b36c50d883ea098a9becb2d62a91ea78e79af9f21686bc143a40582

Transaction to Submit: 0x250284d2fe53ccc6cce10ca33e1aaedd4d676558d94cbc8abc593a419e0a1bcbc7bc5801483454de8b9f1ee4ec54cc11c6896fcc3804b1a8ddb84a45e5a0f96ae88ebf28f03253bc1b36c50d883ea098a9becb2d62a91ea78e79af9f21686bc143a405826502000004007456209b3bd8230c0db53ca22f3f1ebc59060c3d1060b29f407d655ca0c73a4200

Expected Tx Hash: 0x4bd2f95460da3106b740652f2c4dc3f99cf215599f3e401be9f7b0676baa56d4
method:author_submitExtrinsic===> rest :undefined
Error: 1010 Invalid Transaction: "Transaction has a bad signature"
    at /Users/gaoxun/WebstormProjects/dot-sign-server/util.js:25:17
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async main (/Users/gaoxun/WebstormProjects/dot-sign-server/test_api.js:117:26)

**Comment by danforbes** [comment]
Yes, it looks like the issue is that you are running code that is meant for the Polkadot Network on the Westend Network and it looks like there is some difference in the types that go into a signature. I think you need to update this https://github.com/paritytech/txwrapper/blob/09555151e8adbddc9b7d911ab6583297ecfd51e8/examples/polkadot.ts#L50-L51 @joepetrowski can you provide more details? Here's another reference that documents types for Westend https://github.com/polkadot-js/api/blob/master/packages/types-known/src/spec/westend.ts

**Comment by joepetrowski** [comment]
Exactly, change that line and add this one:
```
const registry = getRegistry('Westend', 'westend', specVersion); 
registry.setMetadata(createMetadata(registry, metadataRpc));
```

**Comment by shawn0322** [comment]
The problem has been solved. Thank you very much. 

const registry = getRegistry('Westend', 'westend', specVersion); 
registry.setMetadata(createMetadata(registry, metadataRpc));
