### ISSUE TITLE
In kusama transfer, the transaction is sent successfully, but the transaction cannot be seen in the block explorer

### ISSUE THREAD

**Issue by seancheen** [paritytech/txwrapper#213]
I send a tansfer in kusama with txwrapper, the transaction is sent successfully, but the transaction cannot be seen in the block explorer.
I use WsProvider

const provider = new WsProvider('wss://kusama-rpc.polkadot.io')

`export function rpcToNode(method: string, params: any[] = []): Promise<any> {
    return provider.send(method, params);
}`

`    const actualTxHash = await rpcToNode('author_submitExtrinsic', [tx]);
`

**Comment by emostov** [comment]
The `rpcToNode` you have above looks fine. If you are totally certain your transaction is not in a block you can also check the nodes transaction pool. If it is not in the transaction pool and not in a block then it was rejected before execution of the extrinsic was attempted.

**Comment by roccomuso** [comment]
did you solve this?
you tried to sent multiple tx pheraps? then you gotta keep in mind nonce gotta be incremented

**Comment by seancheen** [comment]
> did you solve this?
> you tried to sent multiple tx pheraps? then you gotta keep in mind nonce gotta be incremented

solved，nonce problem
