### ISSUE TITLE
Can not call more than 5 transfers in 1 utility.batch

### ISSUE THREAD

**Issue by anhcao142** [paritytech/txwrapper#263]
Hi, I tried to call more than 5 transfers using the `utility.batch` method and received `1010: Invalid Transaction: Transaction has a bad signature`. Is that the max number of calls for a batch?

**Comment by emostov** [comment]
No, the error you have is most likely coming from some other issue with the transaction construction. Here is an example that has 18 `balances.transfer`: https://gist.github.com/emostov/199de06b2a6dfbae912be1255aff5426
