### ISSUE TITLE
metadata when running offline

### ISSUE THREAD

**Issue by roccomuso** [paritytech/txwrapper#268]
Since this lib is intended to work offline, does this means polkadot metadata could be provided staticly? or it's suggested to retrieve updated metadata on every run?

**Comment by emostov** [comment]
You can keep the metadata around statically on an offline machine; you will want to make sure you are always using the latest metadata by updating the static asset after each runtime upgrade.

**Comment by roccomuso** [comment]
How often is the runtime upgraded?
I'm not familiar yet with substrate/polkadot

**Comment by emostov** [comment]
Normally it is updated once a month through the governance process. The process can be quicker if there is an urgent bug fix to be pushed through. And in theory it can be slower if the proposal for a runtime upgrade gets rejected.

**Comment by roccomuso** [comment]
I'm trying to understand how metadata is used to build an Extrinsic transaction.
I don't wanna use the polkadot-js (too big of a dependency for my use case), but instead I'm trying to build something smaller, using just the necessary things. I saw there was a `runtime_createExternalSignerPayload` but apparently is available only on the python substrate interface.
A documentation showing how metadata is used to serialize the transaction would be helpful!

**Comment by emostov** [comment]
Unfortunately, the docs for exactly how to create and encode an extrinsic are still in development. You can see the PR here: https://github.com/substrate-developer-hub/substrate-developer-hub.github.io/pull/674.

I think this is also valid implementation of extrinsic construction from a community member that might serve as a reference:
https://github.com/darkfriend77/SubstrateNetApi/blob/d6349a46ec23568510d8b238562391e150ca8095/SubstrateNetApi/MetaDataModel/Extrinsic/ExtrinsicModel.cs#L31

If you do end up making your own lightweight implementation of extrinsic construction I would recommend directing your questions to substrate technical via riot chat room (invite link: https://matrix.to/#/!HzySYSaIhtyWrwiwEV:matrix.org?via=matrix.parity.io&via=matrix.org&via=web3.foundation).
