### ISSUE TITLE
the source code of addSignature 

### ISSUE THREAD

**Issue by jaslin-W** [paritytech/txwrapper#313]
i want to generate a transaction in java. I have construct these params need in  `extrinsic.addSignature(unsigned.address, signature, unsigned);` .https://github.com/paritytech/txwrapper/blob/master/src/createSignedTx.ts#L27
 But i can't see what happen in this method. Where can i get the source code of this method. I m not  familiar with js or ts.
Thanks!

**Comment by emostov** [comment]
Do you have any more details on what exactly you are trying to do? Are you trying to both create and sign extrinsics in Java? Is this for Polkadot?

**Here are some starting points for the polkadot-js code you are referring to:**

https://github.com/polkadot-js/api/blob/a58be2276400d2ac056e515abeb85c6fb9562553/packages/types/src/extrinsic/v4/ExtrinsicSignature.ts#L126

https://github.com/polkadot-js/api/blob/a58be2276400d2ac056e515abeb85c6fb9562553/packages/types/src/extrinsic/v4/ExtrinsicSignature.ts#L113

https://github.com/polkadot-js/api/blob/4e0d430504dac63584c6e44904d2a529a52b9e86/packages/types/src/interfaces/extrinsics/types.ts#L32

https://github.com/polkadot-js/api/blob/4db33b6caf10b807d110d20fa504a705db29eede/packages/types/src/interfaces/extrinsics/definitions.ts#L28

**Depending on exactly what you are trying to do, looking at these links may help as well:**

https://github.com/paritytech/substrate-subxt/blob/master/src/extrinsic/signer.rs

https://github.com/substrate-developer-hub/substrate-developer-hub.github.io/blob/df/integrate/encode-tx/docs/knowledgebase/integrate/encode-txs.md

**Comment by jaslin-W** [comment]
thanks very much . Yes. **i am trying to create and sign extrinsics in Java for polkadot** 
I see this example. 
https://github.com/paritytech/txwrapper/blob/master/src/createSignedTx.ts
I am not clear this example how to generate signed TX.
Should i follow this encode tx rule in this link? 
https://github.com/substrate-developer-hub/substrate-developer-hub.github.io/blob/df/integrate/encode-tx/docs/knowledgebase/integrate/encode-txs.md#transaction-construction
I create a tx object and set these values listed in above link.  And then, i change this tx object to Hex string ? is it right?

**Comment by emostov** [comment]
In general, I would highly recommend using polkadot-js or another javascript library that uses polkadot-js (such as txwrapper) for transaction construction and signing. Polkadot and Kusama use forkless runtime upgrades,  meaning the business logic of the networks gets updated regularly, which requires updates to the metadata and types used for transaction construction. Polkadot-js is set up really well to seamlessly upgrade types and metadata for transaction construction when the network upgrades and I think is the best supported tool for transaction construction in the ecosystem right now.

That being said here is a little bit more info that might help for using Java to construct and sign transactions:

Scale encoding:
The data encoding scheme substrate nodes use.
Wiki on scale info: https://substrate.dev/docs/en/knowledgebase/advanced/codec
Reference implementation in Rust: https://github.com/paritytech/parity-scale-codec

Java TX construction and signing lib:
I also found this transaction library in Java that appears to also have signing functionality. I am not sure how complete it is / if it works, but hopefully it is helpful:
https://github.com/emeraldpay/polkaj/blob/master/docs/05-extrinsics.adoc

> Should i follow this encode tx rule in this link?
This is a starting point, but there is a bit more to it and you will have to look in the substrate source code a bit. You will have to look at the Rust data structures that make up the extrinsic and then look how they are encoded in parity's SCALE codec. You would then submit the SCALE encoded transaction as a hex string.

In Substrate you should probably check out `UncheckedExtrinsic` and how the encoding is implemented with `impl Encode for UncheckedExtrinsic`: https://github.com/paritytech/substrate/blob/1ec8a7f57ba5faac74c09296eab9977fb331c386/primitives/runtime/src/generic/unchecked_extrinsic.rs#L36L49

**Comment by jaslin-W** [comment]
Thanks very much!  @emostov
