### ISSUE TITLE
why there is no field "fee" in method: "methods.balances.transfer"

### ISSUE THREAD

**Issue by yasyzb** [paritytech/txwrapper#314]
when I test the `./examples/polkadot.ts`, I find no place to fill the transfer fee. Does substrate calc fee self? Can we calc the fee when structuring the transaction?

**Comment by emostov** [comment]
Fee calculation depends on some variables that change a little bit block to block. You can get a good estimate of the fee by dry running the transaction, which also gives some other info about the side effects of the transaction. You can use the raw rpc call, or you could also use the Sidecar endpoint: https://github.com/paritytech/substrate-api-sidecar/blob/5936a1c9907d0a2add8c3265121a8f66d20a62f2/src/controllers/transaction/TransactionDryRunController.ts#L9). 

You can also use the fee estimate rpc call `queryInfo`, which gives an approximation of the dispatch info (there is also a Sidecar endpoint for this: https://github.com/paritytech/substrate-api-sidecar/blob/5936a1c9907d0a2add8c3265121a8f66d20a62f2/src/controllers/transaction/TransactionFeeEstimateController.ts#L8

To get the exact fee you need to replicate runtime logic off chain. Sidecar uses a rust crate to do fee calculations and will give you the fees of transactions included in blocks. See here: https://github.com/paritytech/substrate-api-sidecar/blob/5936a1c9907d0a2add8c3265121a8f66d20a62f2/src/controllers/blocks/BlocksController.ts#L50

You can find the full docs for Sidecar here: https://paritytech.github.io/substrate-api-sidecar/dist/
