### ISSUE TITLE
poldot tokenDecimals 10 not 12 ,send tx error

### ISSUE THREAD

**Issue by wittwitt** [paritytech/txwrapper#368]
`Polkadot: {
        ss58Format: constants_1.POLKADOT_SS58_FORMAT,
        tokenDecimals: 12,
        tokenSymbol: 'DOT',
    },`

Polkadot 10???? 
send unit eror ,,
 // 10  000 000 000 ok ,
  // 100 000 000 000  false

**Comment by emostov** [comment]
Hi -

I am not sure I understand the question. But the tokenDecimals for polkadot is 10, not 12. This got updated when the network launched. Here are some articles that explained: https://polkadot.network/tag/redenomination/

For now you should use 10 for the tokenDecimals.

Our code is out of date. We need to update the tokenDecimals here:
https://github.com/paritytech/txwrapper/blob/b54cd88114416e85077dee8a25ae68468bca9a6c/src/util/metadata.ts#L41-L45
