### ISSUE TITLE
Signature can't broadcast at polkadot.js.org/app

### ISSUE THREAD

**Issue by XuNeal** [paritytech/txwrapper#66]
When I broadcast a signature built by txwrapper, I got an error below
`submitExtrinsic(extrinsic: Extrinsic): Hash:: 1010: Invalid Transaction: BadProof`

I had tried changing the genesisHash to `0xb0a8d493285c2df73290dfb7e61f870f17b41801197a149ca93654499ea3dafe` 
and the specVersion to 1045,
 and the method callIndex from 0603 to 0400. but nothing changed, the error is always the same.

Could someone give me some suggestions?

**Comment by amaury1093** [comment]
Could you tell us how you constructed the signature and the extrinsic?

**Comment by XuNeal** [comment]
I changed the testcase in https://github.com/paritytech/txwrapper/blob/528f9ed8454c37cf13fc050eb763c383aafbc043/src/util/testUtil.ts#L19 and https://github.com/paritytech/txwrapper/blob/528f9ed8454c37cf13fc050eb763c383aafbc043/src/util/testUtil.ts#L54, and then I run the 'createSignedTx' tesecase in createSignedTx.spec.ts. I try to broadcast the output at https://polkadot.js.org/apps/#/toolbox
![image](https://user-images.githubusercontent.com/10441775/75204658-680e9900-57ac-11ea-9982-47f14fb95ced.png)

I wonder if the txwrapper is too new for Kusama CC3? Does Kusama CC3 use some old struct?

**Comment by amaury1093** [comment]
There are a lot of parameters you need to tweak yourself: all the parameters in https://github.com/paritytech/txwrapper/blob/master/src/util/types.ts#L17 (except tip and validityPeriod which are optional).

This is an advanced tool: it's the user's responsibility to fetch the blockNumber/blockHash where this tx is going to be valid, fetch the specVersion, the chain's metadataRpc at that specVersion, the account and its nonce etc. In this way, txwrapper is not too new or too old for Kusama CC3: you just need to pass Kusama's exact data into txwrapper.

The test cases in this repo are not test cases for Kusama.

**Comment by psiofxt** [comment]
I used methods from this repo to build my txs offline and it worked fine until the recent releases of the polkadot JS api and am now getting the bad proof like @XuNeal. Unfortunately using previous versions (1.0.1) doesn't work because the other dependencies are set with `^X.X.X` and it seems like there's a dependency hell happening.

Did anything change in the created types (`SignerPayload`, and `ExstrinsicPayload`) ?

The dependency bot seems to not be able to pass tests as well: https://github.com/paritytech/txwrapper/pull/68

**Comment by XuNeal** [comment]
@amaurymartiny  So sorry, I find that it's not the txwrapper's problem,  and it's all because of the input.
@psiofxt After I tried the polkadot-js/api project. I find there are some reasons to cause that problem. 
First, you should use the right nonce which the account should be on chain.
Second, if you use the ImmortalEra, the blockhash should be equal to the geniuses_hash.

I hope that's useful to you.

**Comment by amaury1093** [comment]
@psiofxt [txwrapper@v0.4.8](https://www.npmjs.com/package/@substrate/txwrapper/v/0.4.8) should have the latest @polkadot/api
